FROM golang:1.13.5-alpine as builder

RUN mkdir /build 
ADD . /build/
WORKDIR /build 

RUN go build -o bin/api-server.exe cmd/api/main.go

FROM alpine:3.10.3
WORKDIR /app
COPY --from=builder /build/bin/api-server.exe /app/

ENTRYPOINT ["/app/api-server.exe"]